version: "3.7"

services:
  api:
    image: node:14-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 3001:3001
    working_dir: /api
    volumes:
      - ./api:/api

  client:
    image: node:14-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 3000:3000
    working_dir: /client
    volumes:
      - ./client:/client

  postgres:
    image: postgres
    volumes:
      - henry-countries-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: Post25gres08
      POSTGRES_DB: henry_countries

volumes:
  henry-countries-data:
